openapi: 3.0.0
info:
  title: Product-feedback
  description: Product-feedback app API
  version: 0.1.9

servers:
  - url: https://product-feedback-api-nika.herokuapp.com/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /feedbacks:
    get:
      tags:
        - Feedbacks
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /categories:
    get:
      tags:
        - Categories
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /status:
    get:
      tags:
        - Status
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /feedbacks/new:
    post:
      tags:
        - Feedbacks
      requestBody:
        description: create feedback
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                category_id:
                  type: number
            example:
              title: Node is awesome
              description: Don't use nodemon on server
              category_id: 2
      responses:
        "200":
          description: feedback created
  /users:
    get:
      tags:
        - Users
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /comment:
    post:
      tags:
        - Comments
      requestBody:
        description: create comment
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                feedbackId:
                  type: number
                userId:
                  type: number
            example:
              content: Awesome idea! Trying to find framework-specific projects within the hubs can be tedious
              feedbackId: 1
              userId: 2
      responses:
        "200":
          description: comment created
  /replay:
    post:
      tags:
        - Comments
      requestBody:
        description: create replay
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                replyingTo:
                  type: string
                feedbackId:
                  type: number
                userId:
                  type: number
                commentId:
                  type: number
            example:
              content: While waiting for dark mode, there are browser extensions that will also do the job. Search for 'dark theme' followed by your browser. There might be a need to turn off the extension for sites with naturally black backgrounds though.
              replyingTo: hummingbird1
              feedbackId: 2
              userId: 6
              commentId: 4
      responses:
        "200":
          description: replay created
