openapi: 3.0.0
info:
  title: Product-feedback
  description: Product-feedback app API
  version: 0.1.9

servers:
  - url: https://product-feedback-api-nikanoza.herokuapp.com/api
    description: production server
  - url: http://localhost:3000/api
    description: local server  
paths:
  /feedbacks:
    get:
      tags:
        - Feedbacks 
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string 
                  