openapi: 3.0.0
info:
  title: Product-feedback
  description: Product-feedback app API
  version: 0.1.9

servers:
  - url: https://product-feedback-api-nikanoza.herokuapp.com/api
    description: production server
  - url: http://localhost:3000/api
    description: local server  
paths:
  /feedbacks:
    get:
      tags:
        - Feedbacks 
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string 
  /categories:
    get:
      tags:
        - Categories 
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string    
  /status:
    get:
      tags:
        - Status
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string             
  /feedbacks/new:
    post:
      tags: 
        - Feedbacks
      requestBody:
        description: create feedback
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                category_id: 
                  type: number
            example:
              title: Node is awesome
              description: Don't use nodemon on server    
              category_id: 2
      responses:
        '200':
          description: feedback created
  /users:
    get:
      tags:
        - Users
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string   